server:
  port: 9000
  servlet:
    context-path: /


# User MS
spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - TokenFilter
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/user/**


# Enable detailed logging
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.reactive: DEBUG
    org.springframework.web.server: DEBUG
